import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { dir } from 'i18next'
import { languages } from '../i18n/settings'
import { Footer } from './components/Footer'

import  { NavbarDefault } from './components/NavbarDefault'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    lng: string;
  };
}


export default function RootLayout({children, params: {lng}}: RootLayoutProps ) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <head />
      <body className={inter.className}>

        <NavbarDefault lng={lng} />

        {children}
        <Footer lng={lng} path="" />
      </body>
    </html>
  )
}
