
import "./styles/globals.css";
import { Inter } from "next/font/google";
import { dir } from "i18next";
import { languages } from "../i18n/settings";
import Providers from "./components/providers";

import { Footer } from "./components/Footer";
import { Header } from "./Header";


const inter = Inter({ subsets: ["latin"] });

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { lng } }) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={'bg-light dark:bg-dark'}>
        <Providers>
          <Header />

          {children}
          <Footer lng={lng} path="" />
        </Providers>
      </body>
    </html>
  );
}
